apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: test-pcmsv2-nginx
  name: test-pcmsv2-nginx
  namespace: demo
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: test-pcmsv2-nginx
  template:
    metadata:
      labels:
        app: test-pcmsv2-nginx
    spec:
      containers:
       - name : test-pcmsv2-nginx-containers
         image: $DOCKERHUB_NAMESPACE/$APP_NAME:SNAPSHOT-CRON-BUILD-$BUILD_NUMBER
         resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 10m
              memory: 10Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
            
